---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - include_vars: vars.yml
    - name: Destroy droplet
      digital_ocean:
        unique_name: yes
        state: absent
        command: droplet
        name: "{{ droplet_name }}"
