---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - include_vars: vars.yml
    - name: Create or Start droplet
      digital_ocean:
        unique_name: yes
        state: present
        command: droplet
        name: "{{ droplet_name }}"
        region_id: lon1
        size_id: 512mb
        image_id: ubuntu-16-04-x64
        ssh_key_ids:
          - "06:2a:1e:25:ae:ee:c9:6b:96:58:ae:8e:91:36:81:a3"
        backups_enabled: no
        ipv6: yes
        unique_name: yes
      register: do

    - name: Add new host to inventory
      add_host:
        name: "{{ do.droplet.ip_address }}"
        groups: do
      when: do.droplet is defined

    - name: debug
      debug:
        msg: "{{ do }}"

- hosts: do
  remote_user: root

  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    openvpn_use_pam: no
    openvpn_clients: [thinkpad]
    openvpn_server_options:
     - push "dhcp-option DNS 8.8.8.8"
     - push "redirect-gateway def1 bypass-dhcp"

  roles:
    - Stouts.openvpn
    - routing

  pre_tasks:
    - name: Wait for port 22 to become available.
      local_action: "wait_for port=22 host={{ inventory_hostname }}"

  tasks:
    - name: Download certs
      fetch:
        src: /etc/openvpn/keys/{{ item }}.zip
        dest: keys/
        flat: yes
        fail_on_missing: yes
      with_items: "{{ openvpn_clients }}"

    - name: Start openvpn server
      systemd:
        name: openvpn@server
        state: restarted
        enabled: yes
